apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmware-test
spec:
  count: 2
  podTemplate:
    spec:
      containers:
      - name: vmware-test
      image: gcr.io/poc-project/vmware-test
      ports:
      - containerPort: 5000
  http:
    service:
      spec:
        type: ClusterIP